### ISSUE TITLE
Recent r java issues

### ISSUE THREAD

**Issue by trinker** [craigcitro/r-travis#112]
As of about a week ago my repo that contains java based r packages now errors and I am unsure of how to fix this.  The [repo](https://github.com/trinker/qdap/blob/master/.travis.yml)  utilizes the following .yml:

```
language: java

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - sh -e /etc/init.d/xvfb start
  - sudo R CMD javareconf
  - ./travis-tool.sh aptget_install r-cran-xml 
  - ./travis-tool.sh aptget_install r-cran-gplots
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github cboettig/knitcitations
  - ./travis-tool.sh install_deps
  - Rscript -e "source('http://bioconductor.org/biocLite.R');
      biocLite();
      biocLite('Rgraphviz')"
script: ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change

env:
   global:
     - R_BUILD_ARGS="--compact-vignettes=gs+qpdf" 
     - R_BUILD_ARGS="--resave-data=best" 
     - DISPLAY=:99.0
```

But now errors with:

```
* installing the package to build vignettes
      -----------------------------------
ERROR: dependencies ‘openNLP’, ‘venneuler’, ‘xlsx’ are not available for package ‘qdap’
* removing ‘/tmp/RtmpmgnE7h/Rinst6c5c1aa1ec6d/qdap’
      -----------------------------------
ERROR: package installation failed
The command "./travis-tool.sh run_tests" exited with 1.
Done. Your build exited with 1.
```

The common link between these 3 packages is an rJava/java dependency.  The package passes local CRAN checks.
