### ISSUE TITLE
The command "./travis-tool.sh run_tests" exited with 1.

### ISSUE THREAD

**Issue by TransGirlCodes** [craigcitro/r-travis#142]
The build for my R package fails with the error:

`The command "./travis-tool.sh run_tests" exited with 1.` 

For my travis branch, after following directions on the Wiki, my travis yaml file has:

```
language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - BIOC_USE_DEVEL="FALSE"
```
