### ISSUE TITLE
r_package_binaries ignored?

### ISSUE THREAD

**Issue by markvanderloo** [craigcitro/r-travis#156]
I'm trying to build a package on travis-ci. Before the actual build, I generate the Rd files using roxygen2 and devtools. However, even though I list both under ```r_binary_packages:``` in my ```.travis.yml```, they seem to be ignored. Am I doing something wrong? Below is my ```.travis.yml```

```
language: r

warnings_are_errors: true

r_binary_packages:
  - roxygen2
  - devtools

before_install:
  - cp ./build/DESCRIPTION ./pkg
  - R -q -f roxygen.R
  - cd ./pkg

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change
```
 
I can do  ```R -f try(install.pacackages())``` and so on under ```before_install``` but that seems a lot slower.

In case you're wondering: I prefer to generate documentation during the build process rather than adding the generated Rd files to my github repo. The generated files would pollute my github commit history with changes I did not make myself.

Thanks,
Mark
