### ISSUE TITLE
Cache package install

### ISSUE THREAD

**Issue by hadley** [craigcitro/r-travis#21]
Yet another idea for reducing package install time: http://about.travis-ci.org/docs/user/caching/ discusses the standard travis for caching language specific dependencies between builds.  It may be as simple as:

```
cache:
  bundler: true
  directories:
  - library
```

assuming that we install all packages in library
