### ISSUE TITLE
uploading the check directory to dropbox

### ISSUE THREAD

**Issue by romainfrancois** [craigcitro/r-travis#75]
I played with this this morning. [This directory](https://www.dropbox.com/sh/gttxpckecs65434/Y8KLQS0gqq) has been uploaded to dropbox by travis. This is an intermediate measure but at least is a way to see build artefacts without dumping them in the log file. 

This needs the [`dropbox.sh`](https://github.com/romainfrancois/r-travis/blob/master/scripts/dropbox.sh) file from my fork of `r-travis`, inspired from `https://github.com/andreafabrizi/Dropbox-Uploader` by modified to fit nicely with travis. 

It also needs some dropbox specific environment variables to handle authentification with dropbox etc ...

My `dropbox` branch of dplyr for example has : 

```
env:
  global:
  - ACCESS_LEVEL=sandbox
  - secure: LELmW/uGnmc8gPcJcDMV5SeAy7eieqSrNTqW8mSrSShgu31ifQ9tzd+5U2SxL/LVit+oxT/oyXAKSjX8oebBC8qSZKMR33+kURxq8HHZ6eqhvJv3lh7wjvFpXdPdgr+HrtCqnKBqbMN0oQkMZAtBUTpIwf0K+Zw+eNon0GdYIc4=
  - secure: QOMc+iTz2UspKkm4J6XDNMxzALAzH8NCDR0J+s3JG2VWcHS0m0sbK6rIiTnztzonTP9052HfpgdUY8Culjpww7JamCQ3CYUA83NAdmXLrsSsUWC6emxkw0dCUi2exMVllNfy9uH+Dcj1ytZpDrabeBDS6CF4jbp7wpfMrfJeOO0=
  - secure: L3fKoY3SMpxsaLz/TUIy07j209E5ZCBFaXLEb3j0f+hYc97432xFDcBNjtE8TQ8X0GqnmCxZX/+45QRm2th7Hk2Ei1imIM2OMDQNnBFBnbzqN4qTrGkPCP6YEfKqw8NvxB6GkJEXgxE1zHIhTguicvDSPKNO1SUAirnzkRc1C6M=
  - secure: V94Mz3NGm5e39XPr776K3HMzX8m9Khz3DWwQgjE6gADn2kElm4ZgLYJ+hmTaW1W79vx/GDD6n3whPCP28oocOB/LLVX4zzY5tvjVegSo6gY1wRXPF+HEysjokxlMfVC68qS2qDr4f9FgJb0oREddJ5CxINZOL6suBYj9yzPhafA=
```

The 4 secure lines above are generated by `travis encrypt ENV_VAR=value` for the 4 environment variable that `./dropbox.sh` needs: 

```
APPKEY=xxx
APPSECRET=yyy
ACCESS_LEVEL=sandbox
OAUTH_ACCESS_TOKEN=xxx
OAUTH_ACCESS_TOKEN_SECRET=xxx
```

To get `APPKEY` and `APPSECRET`, we just create a dropbox app. 
Then for the OAUTH_ACCESS_TOKEN and OAUTH_ACCESS_TOKEN_SECRET, I've used the original `https://github.com/andreafabrizi/Dropbox-Uploader` script. When you run it the first time and you follow through, it writes a `~/.dropbox_uploader` file that contains the information. 

This is still a bit involved but this is meant as a proof of concept of uploading whatever we create on travis into dropbox. I guess this could be applied to other things like google drive ...

With a bit of imagination, we could then have things like up to date vignettes, benchmark results. 

Eventually I think it would make sense to have the information not necessarily on dropbox but on some service we would create as a community to make sense and present nicely.
